### ISSUE TITLE
External sites doesn't work after upgrade to NC11

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/apps#21]
### Affected apps
External sites

### Expected behaviour
After upgrade it should work as before or better

### Actual behaviour
Server generates an error after login, have to disable the app at command line with 'occ app:disable external' to get server functional

### Steps to reproduce
1. Upgrade from 10 to 11
2. Log in to server
3. ---

### Server configuration
Operating system:
Ubuntu 16.04.1
Web server: 
Apache2
Database:
MySQL
PHP version:
7

NextCloud log entry:
"reqId":"RhP6WaJ7kXCXcCiJipFV","remoteAddr":"xx.xx.xx.xx","app":"index","message":"Exception: {\"Exception\":\"RuntimeException\",\"Message\":\"image not found: image:boltlogo.png webroot:\\\/nextcloud serverroot:\\\/var\\\/www\\\/html\\\/nextcloud\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/external\\\/appinfo\\\/app.php(38): OC\\\\URLGenerator->imagePath('external', 'boltlogo.png')\\n#1 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/NavigationManager.php(64): OC_App::{closure}()\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/app.php(736): OC\\\\NavigationManager->getAll()\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/TemplateLayout.php(84): OC_App::getNavigation()\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(232): OC\\\\TemplateLayout->__construct('user', 'files')\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/public\\\/AppFramework\\\/Http\\\/TemplateResponse.php(157): OC_Template->fetchPage()\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(113): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#7 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#8 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#11 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#12 \\\/var\\\/www\\\/html\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/URLGenerator.php\",\"Line\":206}","level":3,"time":"2017-01-03T14:43:03+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/","user":"foobar","version":"11.0.0.10"}

**Comment by putt1ck** [comment]
Now traced to use of a manual upgrade process, which didn't copy the logos from the old apps/external/img - although maybe it should be less sensitive to missing logo files?
